from rest_framework import serializers
from django.contrib.auth.password_validation import validate_password
from .models import User, Profile


class ProfileSerializer(serializers.ModelSerializer): # ModelSerializer is a base class for serializers that work with models, iit converts models to/from JSON
    """Serializer for Profile model"""
    class Meta:
        model = Profile # serializer need to know which db table to use
        fields = ['id', 'bio', 'avatar', 'address', 'updated_at'] # fields are the fields that will be serialized
        read_only_fields = ['updated_at'] #  update_at is not editable, it is auto generated by the model


class UserSerializer(serializers.ModelSerializer):
    """Basic User serializer for listing and basic operations"""
    class Meta:
        model = User
        fields = ['id', 'email', 'phone', 'role', 'date_joined', 'is_active']
        read_only_fields = ['id', 'date_joined']


class UserDetailSerializer(serializers.ModelSerializer):
    """User serializer with nested profile"""
    profile = ProfileSerializer(read_only=True) # profile is a nested serializer, it is a serializer for the Profile model
    
    class Meta:
        model = User # serializer need to know which db table to use
        fields = ['id', 'username', 'email', 'phone', 'role', 'first_name', 'last_name', 
                  'date_joined', 'is_active', 'profile'] # fields are the fields that will be serialized
        read_only_fields = ['id', 'date_joined']

# UserRegistrationSerializer is a serializer for user registration with password validation
class UserRegistrationSerializer(serializers.ModelSerializer):
    """Serializer for user registration with password validation"""
    password = serializers.CharField(write_only=True, required=True, validators=[validate_password])
    
    class Meta:
        model = User
        fields = ['username', 'email', 'password', 'phone', 'role', 
                  'first_name', 'last_name']
        extra_kwargs = { # extra_kwargs are the extra keyword arguments that will be used to validate the data, makes email and role required even if models allows them to be null
            'email': {'required': True, 'unique': True},
            'role': {'required': True},
        }
    
    def create(self, validated_data):
        password = validated_data.pop('password')
        user = User.objects.create_user(password=password, **validated_data)
        return user


class UserUpdateSerializer(serializers.ModelSerializer):
    """Serializer for updating user information"""
    class Meta:
        model = User
        fields = ['username', 'email', 'phone', 'first_name', 'last_name']
        extra_kwargs = { # extra_kwargs are the extra keyword arguments that will be used to validate the data, makes email not required even if models allows it to be null
            'email': {'required': False},
        }
    
    def validate_email(self, value):
        user = self.instance
        if User.objects.filter(email=value).exclude(pk=user.pk).exists():
            raise serializers.ValidationError("A user with this email already exists.")
        return value


class ProfileUpdateSerializer(serializers.ModelSerializer): # ProfileUpdateSerializer is a serializer for updating profile information
    """Serializer for updating profile information"""
    class Meta:
        model = Profile # serializer need to know which db table to use
        fields = ['bio', 'avatar', 'address']

